"""empty message

Revision ID: 7ce483cf3416
Revises: 
Create Date: 2022-05-09 17:51:18.733035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce483cf3416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cash_id'), 'Cash', ['id'], unique=True)
    op.create_table('Research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('research_and_development', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Research_id'), 'Research', ['id'], unique=True)
    op.create_table('Research_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('research_and_development', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Research_year_id'), 'Research_year', ['id'], unique=True)
    op.create_table('SEC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SEC_id'), 'SEC', ['id'], unique=True)
    op.create_table('Sharesoutstandinghistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sharesoutstandinghistory_id'), 'Sharesoutstandinghistory', ['id'], unique=True)
    op.create_table('macrotrends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macrotrends_id'), 'macrotrends', ['id'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('new_ticker', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=True)
    op.create_table('institutional_holdings_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('file_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('alg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_holdings_2_id'), 'institutional_holdings_2', ['id'], unique=True)
    op.create_table('institutional_holdings_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('file_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_holdings_raw_id'), 'institutional_holdings_raw', ['id'], unique=True)
    op.create_table('institutional_holdings_raw_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('file_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_holdings_raw_3_id'), 'institutional_holdings_raw_3', ['id'], unique=True)
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('listed', sa.Boolean(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('formerly_names', sa.String(), nullable=True),
    sa.Column('current_name', sa.String(), nullable=True),
    sa.Column('original_names', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_names_id'), 'names', ['id'], unique=True)
    op.create_table('number_of_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('last_object_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_number_of_objects_id'), 'number_of_objects', ['id'], unique=True)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_director', sa.Boolean(), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=True),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=True),
    sa.Column('is_other', sa.Boolean(), nullable=True),
    sa.Column('officer_title', sa.String(), nullable=True),
    sa.Column('other_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=True)
    op.create_table('transactions_and_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('empty', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_ticker', sa.String(), nullable=True),
    sa.Column('company_cik', sa.String(), nullable=True),
    sa.Column('period_of_report', sa.DateTime(), nullable=True),
    sa.Column('file_date', sa.DateTime(), nullable=True),
    sa.Column('period_ending', sa.DateTime(), nullable=True),
    sa.Column('issuer_cik', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=True),
    sa.Column('issuer_ticker', sa.String(), nullable=True),
    sa.Column('security_title', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_form_type', sa.String(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=True),
    sa.Column('equity_swap_involved', sa.String(), nullable=True),
    sa.Column('transaction_shares', sa.Float(), nullable=True),
    sa.Column('shares_owned_following_transaction', sa.Float(), nullable=True),
    sa.Column('transaction_price_per_share', sa.Float(), nullable=True),
    sa.Column('underlying_security_title', sa.String(), nullable=True),
    sa.Column('conversion_or_exercise_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('exercise_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_acquired_disposed_code', sa.String(), nullable=True),
    sa.Column('direct_or_indirect_ownership', sa.String(), nullable=True),
    sa.Column('nature_of_ownership', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_and_holdings_id'), 'transactions_and_holdings', ['id'], unique=True)
    op.create_table('uk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uk_id'), 'uk', ['id'], unique=True)
    op.create_table('association_owners',
    sa.Column('owners_id', sa.Integer(), nullable=True),
    sa.Column('transactions_and_holdings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['transactions_and_holdings_id'], ['transactions_and_holdings.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_owners')
    op.drop_index(op.f('ix_uk_id'), table_name='uk')
    op.drop_table('uk')
    op.drop_index(op.f('ix_transactions_and_holdings_id'), table_name='transactions_and_holdings')
    op.drop_table('transactions_and_holdings')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_number_of_objects_id'), table_name='number_of_objects')
    op.drop_table('number_of_objects')
    op.drop_index(op.f('ix_names_id'), table_name='names')
    op.drop_table('names')
    op.drop_index(op.f('ix_institutional_holdings_raw_3_id'), table_name='institutional_holdings_raw_3')
    op.drop_table('institutional_holdings_raw_3')
    op.drop_index(op.f('ix_institutional_holdings_raw_id'), table_name='institutional_holdings_raw')
    op.drop_table('institutional_holdings_raw')
    op.drop_index(op.f('ix_institutional_holdings_2_id'), table_name='institutional_holdings_2')
    op.drop_table('institutional_holdings_2')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_macrotrends_id'), table_name='macrotrends')
    op.drop_table('macrotrends')
    op.drop_index(op.f('ix_Sharesoutstandinghistory_id'), table_name='Sharesoutstandinghistory')
    op.drop_table('Sharesoutstandinghistory')
    op.drop_index(op.f('ix_SEC_id'), table_name='SEC')
    op.drop_table('SEC')
    op.drop_index(op.f('ix_Research_year_id'), table_name='Research_year')
    op.drop_table('Research_year')
    op.drop_index(op.f('ix_Research_id'), table_name='Research')
    op.drop_table('Research')
    op.drop_index(op.f('ix_Cash_id'), table_name='Cash')
    op.drop_table('Cash')
    # ### end Alembic commands ###
