
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

COPY ./requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y build-essential libpoppler-cpp-dev pkg-config python-dev tesseract-ocr ocrmypdf ghostscript
RUN pip install --upgrade pip 
RUN pip install -r /app/requirements.txt 
COPY . /app
